debug: false
uuid: 009c1f63-bf7b-4e43-acd5-4c6fcf70db6c
token_id: O4iP3fvwzLYyzZWg
token: Oka109q2ARR26XMvW1MBfzvuFExS9yuLtpMUyfqT3xA5u463zq8ohwBHIbjHJven
api:
  host: 0.0.0.0
  port: 4040
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/pika-pro-barely.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/pika-pro-barely.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://80-youtu420-pte-toamnbke2sm.ws-us107.gitpod.io'
